name: E2E Tests (Maestro)

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - android
          - ios
          - both
        required: true
        description: 'Platform to test'
      profile:
        type: choice
        options:
          - development
          - preview
        required: false
        description: 'Build profile to test'
        default: preview

jobs:
  # Build Android for testing
  build_android:
    name: Build Android
    if: ${{ inputs.platform == 'android' || inputs.platform == 'both' }}
    type: build
    params:
      platform: android
      profile: ${{ inputs.profile || 'preview' }}
      message: 'E2E Test Build'

  # Build iOS simulator for testing
  build_ios:
    name: Build iOS Simulator
    if: ${{ inputs.platform == 'ios' || inputs.platform == 'both' }}
    type: build
    params:
      platform: ios
      profile: ${{ inputs.profile || 'preview' }}
      message: 'E2E Test Build'

  # Run Maestro tests on Android
  maestro_android:
    name: Android E2E Tests
    needs: [build_android]
    if: ${{ inputs.platform == 'android' || inputs.platform == 'both' }}
    type: maestro
    environment: preview
    runs_on: linux-large-nested-virtualization
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      flow_path: ./maestro
      retries: 2
      record_screen: true

  # Run Maestro tests on iOS
  maestro_ios:
    name: iOS E2E Tests
    needs: [build_ios]
    if: ${{ inputs.platform == 'ios' || inputs.platform == 'both' }}
    type: maestro
    environment: preview
    runs_on: macos-medium
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      flow_path: ./maestro
      retries: 2
      record_screen: true

  # Test summary
  test_summary:
    name: Test Summary
    after: [maestro_android, maestro_ios]
    type: doc
    params:
      md: |
        # E2E Test Results 🧪

        ## Test Configuration
        - **Platform**: ${{ inputs.platform }}
        - **Profile**: ${{ inputs.profile || 'preview' }}

        ## Results
        Check the Maestro test artifacts for detailed results and screen recordings.

        ## Troubleshooting
        If tests fail:
        1. Check the screen recordings in the artifacts
        2. Review the Maestro flow logs
        3. Ensure the app is properly configured for the test environment
