name: OTA Update

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        options:
          - staging
          - production
        required: true
        description: 'Update channel to publish to'
      message:
        type: string
        required: false
        description: 'Update message/description'

jobs:
  # Production updates
  update_production:
    name: Update Production Channel
    if: ${{ inputs.channel == 'production' }}
    type: update
    environment: production
    params:
      channel: production
      message: ${{ inputs.message || 'OTA Update' }}

  # Staging updates
  update_staging:
    name: Update Staging Channel
    if: ${{ inputs.channel == 'staging' }}
    type: update
    environment: preview
    params:
      channel: staging
      message: ${{ inputs.message || 'OTA Update' }}
