name: Preview Build

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - android
          - ios
          - both
        required: true
        description: 'Platform to build preview for'
      include_update:
        type: boolean
        required: false
        default: true
        description: 'Publish OTA update'
      message:
        type: string
        required: false
        description: 'Build message/description'

jobs:
  # Build Android preview for internal testing
  build_android:
    name: Build Android Preview
    if: ${{ inputs.platform == 'android' || inputs.platform == 'both' }}
    type: build
    params:
      platform: android
      profile: preview
      message: ${{ inputs.message || 'Preview build' }}

  # Build iOS preview for simulator testing
  build_ios:
    name: Build iOS Preview
    if: ${{ inputs.platform == 'ios' || inputs.platform == 'both' }}
    type: build
    params:
      platform: ios
      profile: preview
      message: ${{ inputs.message || 'Preview build' }}

  # Publish an OTA update for quick testing
  publish_update:
    name: Publish Preview Update
    if: ${{ inputs.include_update }}
    type: update
    params:
      branch: ${{ github.ref_name }}
      message: ${{ inputs.message || 'Preview update' }}
